### ISSUE TITLE
Ability to limit class extensions based on add-on installed with min/max version check

### ISSUE THREAD

**Issue by ticktackk** [Xon/XenForo2-StandardLib#2]
This will help a lot in avoiding the issues when XF changes the method signature or does some kind of severe changes to the class and the add-on developer would have to make use `class_alias` to support both older version and the newer version.

Current example is the `XF:UserAlert` repository where the `insertAlert` was changed.

**Comment by Xon** [comment]
`Templater::fnReactions` is another example
